#!/bin/sh

if [ $# -ne 1 ]; then
    echo "Usage: removesite PROJECT_BRANCH_PATH"
    exit 0
fi

PROJECT_DIR=$1
SERVICE_DIR=$PROJECT_DIR/service

_verify_project_dir () {
    if [ ! -d $PROJECT_DIR ]; then
        echo "Error: project dir '$PROJECT_DIR' not found."
        return 1
    fi
}

_remove () {
    echo "Remove project '$PROJECT_DIR'."
    for f in $SERVICE_DIR/*_remove.sh
    do
        echo "Run '$f'"
        sh $f
    done
}

_verify_project_dir || return 1
_remove
sudo rm -rf $PROJECT_DIR

if [ "$SITES_HOME" != "" ] && [ -d $SITES_HOME ]; then
    find $SITES_HOME -depth -type d -empty -exec sudo rmdir {} \;
fi
