#!/bin/sh

sitegenparse $1 remove || exit 1

PROJECT_DIR=$1

_verify_project_dir () {
    if [ ! -d $PROJECT_DIR ]; then
        echo "Error: project dir '$PROJECT_DIR' not found."
        return 1
    fi
}

_verify_project_dir || return 1
sudo rm -rf $PROJECT_DIR

if [ "$SITES_HOME" != "" ] && [ -d $SITES_HOME ]; then
    find $SITES_HOME -depth -type d -empty -exec sudo rmdir {} \;
fi
