#!/bin/sh

makesiteparse $1 remove || exit 0

PROJECT_DIR=$1

if [ ! -d $PROJECT_DIR ]; then
    echo "ERROR: Project dir '$PROJECT_DIR' not found." 1>&2
    exit 0
fi
sudo rm -rf $PROJECT_DIR

if [ ! -z "$SITES_HOME" ] && [ -d $SITES_HOME ]; then
    find $SITES_HOME -depth -type d -empty -exec sudo rmdir {} \;
fi
