#!/bin/sh

if [ $# -ne 1 ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    echo "Usage: removesite PROJECT_BRANCH_PATH"
    echo "\n'removesite' part of sitegen scripts. Activate remove hooks for target project and remove project dir."
    exit 0
fi

sitegenparse $1 remove

PROJECT_DIR=$1

_verify_project_dir () {
    if [ ! -d $PROJECT_DIR ]; then
        echo "Error: project dir '$PROJECT_DIR' not found."
        return 1
    fi
}

_verify_project_dir || return 1
sudo rm -rf $PROJECT_DIR

if [ "$SITES_HOME" != "" ] && [ -d $SITES_HOME ]; then
    find $SITES_HOME -depth -type d -empty -exec sudo rmdir {} \;
fi
