#!/bin/sh
if [ $# -ne 1 ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    echo "Usage: updatesite PROJECT_BRANCH_PATH"
    echo "\n'updatesite' part of sitegen scripts. Activate update hooks for target project."
    exit 0
fi

sitegenparse $1 update
